package views;
import Models.Kitap;
import Patterns.AdinaGöreSiralamaStrategy;
import Patterns.KitapSiralamaStrategy;
import Patterns.KullaniciIDGetirme;
import Patterns.SayfaSayisinaGoreSiralama;
import Patterns.YazarAdinaGöreSiralama;
import java.util.ArrayList;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import service.PersonelIslemleri;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gamze
 */
public class KitaplariListele extends javax.swing.JFrame {
    DefaultTableModel model;
    PersonelIslemleri islemler=new PersonelIslemleri();
    private KitapSiralamaStrategy siralamaStrategy;
    KullaniciIDGetirme kullanici = KullaniciIDGetirme.getKullanici();
    
   
   

    /**
     * Creates new form KitaplariListele
     */
    public KitaplariListele() {
        
        initComponents();
        model=(DefaultTableModel)kitapTablosu.getModel();
        kitaplariGoruntule();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        aramaCubugu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        kitapTablosu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buttonAdSırala = new javax.swing.JButton();
        buttonYazarSırala = new javax.swing.JButton();
        buttonSayfaSırala = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        aramaCubugu.setBackground(new java.awt.Color(242, 242, 242));
        aramaCubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aramaCubuguKeyReleased(evt);
            }
        });

        kitapTablosu.setBackground(new java.awt.Color(242, 242, 242));
        kitapTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kitap ID", "Kitap Adı", "Yazar", "Sayfa Sayısı", "Yayınevi", "Kitap Türü", "Kategori", "Basın Yılı", "Kitaplık", "Raf", "Barkod Sayısı", "Ekleyen Personel", "Eklenme Tarihi", "Durum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(kitapTablosu);
        if (kitapTablosu.getColumnModel().getColumnCount() > 0) {
            kitapTablosu.getColumnModel().getColumn(0).setResizable(false);
            kitapTablosu.getColumnModel().getColumn(1).setResizable(false);
            kitapTablosu.getColumnModel().getColumn(2).setResizable(false);
            kitapTablosu.getColumnModel().getColumn(3).setResizable(false);
            kitapTablosu.getColumnModel().getColumn(4).setResizable(false);
            kitapTablosu.getColumnModel().getColumn(5).setResizable(false);
            kitapTablosu.getColumnModel().getColumn(6).setResizable(false);
            kitapTablosu.getColumnModel().getColumn(7).setResizable(false);
            kitapTablosu.getColumnModel().getColumn(8).setResizable(false);
            kitapTablosu.getColumnModel().getColumn(9).setResizable(false);
            kitapTablosu.getColumnModel().getColumn(10).setResizable(false);
            kitapTablosu.getColumnModel().getColumn(11).setResizable(false);
            kitapTablosu.getColumnModel().getColumn(12).setResizable(false);
            kitapTablosu.getColumnModel().getColumn(13).setResizable(false);
        }

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back-2-icon.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        buttonAdSırala.setBackground(new java.awt.Color(255, 102, 102));
        buttonAdSırala.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonAdSırala.setText("Kitapları Adına Göre Sırala");
        buttonAdSırala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdSıralaActionPerformed(evt);
            }
        });

        buttonYazarSırala.setBackground(new java.awt.Color(255, 102, 102));
        buttonYazarSırala.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonYazarSırala.setText("Yazar Adına Göre Sırala");
        buttonYazarSırala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonYazarSıralaActionPerformed(evt);
            }
        });

        buttonSayfaSırala.setBackground(new java.awt.Color(255, 102, 102));
        buttonSayfaSırala.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonSayfaSırala.setText("Sayfa Sayısına Göre Sırala");
        buttonSayfaSırala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSayfaSıralaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KİTAPLARI LİSTELE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(273, 273, 273)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonAdSırala, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonYazarSırala, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSayfaSırala, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(aramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(buttonAdSırala)
                        .addGap(39, 39, 39)
                        .addComponent(buttonYazarSırala)
                        .addGap(26, 26, 26)
                        .addComponent(buttonSayfaSırala)))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void dinamikAra(String ara){
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(model);
        kitapTablosu.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(ara));
        
    }
     
    private void aramaCubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aramaCubuguKeyReleased
        String ara=aramaCubugu.getText();
        dinamikAra(ara);
    }//GEN-LAST:event_aramaCubuguKeyReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
       String unvan = kullanici.getUnvan();
       
       if(unvan.equals("Personel")){
            PersonelEkrani personelEkrani = new PersonelEkrani();
            personelEkrani.setVisible(true);
            this.dispose();
        }else if (unvan.equals("Öğrenci")){
            ÖğrenciEkrani ogEkrani = new ÖğrenciEkrani();
            ogEkrani.setVisible(true);
            this.dispose();
                
        }else if (unvan.equals("Akademisyen")){
            ÖğrenciEkrani oEkrani=new ÖğrenciEkrani();
            oEkrani.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void buttonAdSıralaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdSıralaActionPerformed
         // "Adına Göre Sırala" butonuna basıldığında çalışacak kod
        AdinaGöreSiralamaStrategy adinaGoreSiralama = new AdinaGöreSiralamaStrategy();
        islemler.setSiralamaStrategy(adinaGoreSiralama);
        ArrayList<Kitap> kitaplar = new ArrayList<>();
        kitaplar = islemler.kitaplariAdinaGoreListele(kitaplar);
        sirala(kitaplar);
          
    }//GEN-LAST:event_buttonAdSıralaActionPerformed

    private void buttonYazarSıralaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonYazarSıralaActionPerformed
        YazarAdinaGöreSiralama yazarAdinaGöreSiralama=new YazarAdinaGöreSiralama();
        islemler.setSiralamaStrategy(yazarAdinaGöreSiralama);
        ArrayList<Kitap> kitaplar = new ArrayList<>();
        kitaplar = islemler.kitaplariAdinaGoreListele(kitaplar);
        sirala(kitaplar);
    }//GEN-LAST:event_buttonYazarSıralaActionPerformed

    private void buttonSayfaSıralaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSayfaSıralaActionPerformed
        SayfaSayisinaGoreSiralama sayfaSayisinaGoreSiralama=new SayfaSayisinaGoreSiralama();
        islemler.setSiralamaStrategy(sayfaSayisinaGoreSiralama);
        ArrayList<Kitap> kitaplar = new ArrayList<>();
        kitaplar = islemler.kitaplariAdinaGoreListele(kitaplar);
        sirala(kitaplar);
    }//GEN-LAST:event_buttonSayfaSıralaActionPerformed
     
    /**
     * @param args the command line arguments
     */

     public void kitaplariGoruntule() {
        model.setRowCount(0);
        ArrayList<Kitap> kitaplar = new ArrayList<Kitap>();
        kitaplar = islemler.kitaplariListele();

        if (kitaplar != null ) {
            for (Kitap kitap :kitaplar) {
                Object[] eklenecek = {kitap.getKitapID(),kitap.getKitap_adi(),kitap.getYazar(),kitap.getSayfa_sayisi(),kitap.getYayinevi(),
                kitap.getKitap_türü(),kitap.getKategori(),kitap.getBasin_yili(),kitap.getKitaplik_adi(),kitap.getRaf(),kitap.getBarkod_sayisi(),kitap.getEkleyen(),kitap.getEklenme_tarihi(),kitap.getDurum()};
                model.addRow(eklenecek);
            }
            
        }
        
        kitaplar = islemler.kitaplariListele();
        
        
        
    }
     public void sirala(List<Kitap> kitaplar){
          model.setRowCount(0);

        if (kitaplar != null) {
            for (Kitap kitap : kitaplar) {
                Object[] eklenecek = {kitap.getKitapID(), kitap.getKitap_adi(), kitap.getYazar(), kitap.getSayfa_sayisi(), kitap.getYayinevi(),
                        kitap.getKitap_türü(), kitap.getKategori(), kitap.getBasin_yili(), kitap.getKitaplik_adi(), kitap.getRaf(), kitap.getBarkod_sayisi(),
                        kitap.getEkleyen(), kitap.getEklenme_tarihi(), kitap.getDurum()};
                model.addRow(eklenecek);
            }
        }
    }
     
    
       
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KitaplariListele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KitaplariListele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KitaplariListele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KitaplariListele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KitaplariListele().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aramaCubugu;
    private javax.swing.JButton buttonAdSırala;
    private javax.swing.JButton buttonSayfaSırala;
    private javax.swing.JButton buttonYazarSırala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable kitapTablosu;
    // End of variables declaration//GEN-END:variables
}
